### ISSUE TITLE
Fiktív Probléma-Bill Gates megette a kenyeremet!!!

### ISSUE THREAD

**Issue by Havasisovago** [Havasisovago/Remes-her-RKSZ#4]
A bizonyos kenőmájas kenyerem ketté volt vágva és ő az asztalról elvette.
Mi a teendő kedves kejlesztő társaim ez ügyben?

**Comment by SzenesBence** [comment]
@Havasisovago  Figyelmébe ajánlom a kenőmájas kenyérvisszakérését, hogyha már elfogyasztotta vagy nem adja vissza, ez esetben ajánlom a Pofon.exe 2.0 fájl futtatását a siker érdekében.
